title: Ravi Vadlamani
description: Undergraduate Research Assistant at Ryerson University
show_downloads: true
google_analytics: UA-157504857-1
theme: jekyll-theme-cayman

github:
  repository_url: https://www.linkedin.com/in/ravi-vadlamani/
  zip_url: https://github.com/ravi-vadlamani/test-site/raw/master/resume-ravi-vadlamani.pdf
  tar_url: https://github.com/ravi-vadlamani
  